# rust-toolchain.toml - Toolchain overrides file
# This file declares the Rust toolchain used by the project.
# Documentation: https://ehuss.github.io/rustup/overrides.html
[toolchain]
channel = "1.87.0"
